version: "2"
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - misspell
  settings:
    gosec:
      excludes:
        - G104
        - G304
