export const enum PermissionSlug {
  ItemView = "items.view",
  ItemCreate = "items.create",
  ItemEdit = "items.edit",
  ItemDelete = "items.delete",
  CategoryView = "categories.view",
  CategoryCreate = "categories.create",
  CategoryEdit = "categories.edit",
  CategoryDelete = "categories.delete",
  FormView = "forms.view",
  FormCreate = "forms.create",
  FormEdit = "forms.edit",
  FormDelete = "forms.delete",
  WorkflowView = "workflows.view",
  WorkflowCreate = "workflows.create",
  WorkflowEdit = "workflows.edit",
  WorkflowDelete = "workflows.delete",
}
